all:
	jpm xpi
	jpm run

# Build the addon
xpi:
	jpm xpi

e10s:
	jpm -b /Applications/FirefoxDeveloperEdition.app/Contents/MacOS/firefox run

# Load a clean Firefox profile and the addon
run:
	jpm run
